// src/categories/ai-videos/index.js
// AI Videos — every eligible scene is GENERATED by an AI video model (Kling browser
// bridge by default, or Veo API) instead of downloaded.
//
// THIS FOLDER IS THE WHOLE FEATURE. Everything AI-Videos-specific lives here and
// nowhere else, so adding a capability = editing one file in src/categories/ai-videos/:
//   index.js          — this descriptor (id/label/formats/generation) + pipeline entry
//   pipeline.js       — the isolated script → clips flow (ordered, named stages)
//   script-input.js   — normalize pasted story/link → clean script text
//   source-loader.js  — secure local-document/public-URL text extraction
//   scene-planner.js  — script → quality-aware scene beats
//   prompt-generator.js — per-scene → styled generation prompt
//   README.md         — how the module is laid out + how to extend it
//
// Two ways AI Videos runs:
//   • Narration-first: the normal build pipeline forces the ai-video lane
//     (_applyVeoScope scope='all' via generation === 'ai-video'), with stock fallback.
//   • Script-first: paste/import/load a story → pipeline.js turns it into generated clips
//     with no voiceover required. See pipeline.js for the stage list.
'use strict';

module.exports = {
    id: 'aiVideos',
    label: '🤖 AI Videos (all footage AI-generated)',
    // includes the old ai-stories aliases so anything saved under the old name still resolves.
    aliases: ['aivideos', 'ai-videos', 'ai_videos', 'aistories', 'ai-stories', 'ai_stories', 'pureai', 'purelyai'],
    allowedFormats: ['aiVideo'], // its own format — documentary/listicle do not apply
    hasPresenter: false,
    generation: 'ai-video',
    scriptFirst: true, // takes a written script instead of (or before) audio narration
    // Lazy entry to the isolated script-first pipeline (avoids loading it unless used).
    get pipeline() { return require('./pipeline'); },
};
