// src/categories/ai-videos.js
// AI Videos — every eligible B-roll scene is GENERATED by an AI video model
// (Kling browser bridge by default, or Veo API) instead of downloaded. Reuses the
// existing ai-video lane (_applyVeoScope scope='all' → sourceHint='ai-video' →
// footage-manager Kling/Veo dispatch, with graceful stock fallback on any miss).
//
// P4 makes this a first-class, selectable production mode driven off `generation`.
// The script-FIRST input (a written story/link instead of audio narration) + the
// per-scene prompt-generation orchestration are P7; today AI Videos is narrated
// like the others but sources all its visuals from the generator.
'use strict';

module.exports = {
    id: 'aiVideos',
    label: '🤖 AI Videos (all footage AI-generated)',
    // includes the old ai-stories aliases so anything saved under the old name still resolves.
    aliases: ['aivideos', 'ai-videos', 'ai_videos', 'aistories', 'ai-stories', 'ai_stories', 'pureai', 'purelyai'],
    allowedFormats: ['aiVideo'], // its own format lands in P7 — documentary/listicle do not apply
    hasPresenter: false,
    generation: 'ai-video',
};
